# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello_world.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hello_world.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hello_world.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe3\x01\n\x07Greeter\x12)\n\tsay_hello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x38\n\x16say_stream_hello_reply\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00(\x01\x12\x38\n\x16say_hello_stream_reply\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x30\x01\x12\x39\n\x15say_hello_bidi_stream\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_world_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=21
  _globals['_HELLOREQUEST']._serialized_end=49
  _globals['_HELLOREPLY']._serialized_start=51
  _globals['_HELLOREPLY']._serialized_end=80
  _globals['_GREETER']._serialized_start=83
  _globals['_GREETER']._serialized_end=310
# @@protoc_insertion_point(module_scope)
